Enhancement/51 backup wasabi
UAL-RE/redata-iac pull request #52
Opened 2023-11-01 01:41 UTC by yhan818

See issue https://github.com/UAL-RE/redata-iac/issues/51

2023-11-01 01:42 UTC, yhan818 commented
There is one request not implemented yet (remove old backup).

2023-11-01 15:54 UTC, zoidy requested changes
The script looks good, just a few simple requests. Also, since the issue this PR references isn't fully addressed, I recommend not merging it until it is. Alternatively, split off the part that remains unaddressed into its own issue

2023-11-01 15:54 UTC, zoidy commented on scripts/backup2wasabi.sh
> +    mkdir "./log"
Is there a reason this one is a relative path but all the other paths in this file are absolute?

2023-11-01 15:54 UTC, zoidy commented on scripts/backup2wasabi.sh
> +    LOG_FILE="/home/curator/codes/LD_Cool_P/curation/scripts/log/curation2_bk_log_${TIMESTAMP}.log"
extra tab is present

2023-11-01 15:54 UTC, zoidy commented on scripts/backup2wasabi.sh
> +
Please provide examples/documentation of how to run this script.  Also, please provide instructions on how to install the aws dependency

2023-11-01 19:49 UTC, yhan818 commented on scripts/backup2wasabi.sh
> +    mkdir "./log"
right. shall use the absolute path

2023-11-03 04:34 UTC, yhan818 commented on scripts/backup2wasabi.sh
> +
DONE

2023-11-03 04:38 UTC, yhan818 commented on scripts/backup2wasabi.sh
> +    mkdir "./log"
I created a new issue for removing old copies.

2023-11-10 05:07 UTC, yhan818 commented on scripts/backup2wasabi.sh
> +    mkdir "./log"
Updated the log. see the latest commit.

2023-11-13 14:49 UTC, zoidy approved these changes

2023-11-13 17:50 UTC, merged